# Generated by Django 4.2.4 on 2023-08-31 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.ImageField(max_length=10, upload_to='')),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_title', models.CharField(max_length=100)),
                ('make_year', models.IntegerField()),
                ('make_month', models.CharField(blank=True, max_length=100, null=True)),
                ('car_manufacturer', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_version', models.CharField(blank=True, max_length=100, null=True)),
                ('car_color', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(choices=[('lpg', 'LPG'), ('cng', 'CNG'), ('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=25)),
                ('transmission_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=25)),
                ('car_owner', models.CharField(choices=[('first owner', 'First Owner'), ('second owner', 'Second Owner'), ('third owner', 'Third Owner'), ('fourth owner or more', 'Fourth Owner or More')], default='first owner', max_length=25)),
                ('kilometer_driven', models.IntegerField(blank=True, null=True)),
                ('expected_selling_price', models.IntegerField()),
                ('registration_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('taxi', 'Taxi')], default='individual', max_length=25)),
                ('insurance_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third party', 'Third Party'), ('expired', 'Expired')], default='expired', max_length=25)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('car_description', models.TextField(blank=True, null=True)),
                ('car_post_date', models.DateField(default=datetime.datetime.now)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='media/car_images/')),
                ('car_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=25)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck'), ('Tractor', 'Tractor'), ('Auto Rickshaw', 'Auto Rickshaw'), ('Agriculture Instrument', 'Agriculture Instrument')], default='Car', max_length=25)),
                ('car_owner_phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('car_city', models.CharField(choices=[('Garhwa', 'Garhwa'), ('Palamu', 'Palamu'), ('Latehar', 'Latehar'), ('Chatra', 'Chatra'), ('Hazaribagh', 'Hazaribagh'), ('Koderma', 'Koderma'), ('Giridih', 'Giridih'), ('Ramgarh', 'Ramgarh'), ('Bokaro', 'Bokaro'), ('Dhanbad', 'Dhanbad'), ('Gumla', 'Gumla'), ('Lohardaga', 'Lohardaga'), ('Simdega', 'Simdega'), ('Ranchi', 'Ranchi'), ('Khunti', 'Khunti'), ('West Singhbhum', 'West Singhbhum'), ('Saraikela Kharsawan', 'Saraikela Kharsawan'), ('East Singhbhum', 'East Singhbhum'), ('Jamtara', 'Jamtara'), ('Deoghar', 'Deoghar'), ('Dumka', 'Dumka'), ('Pakur', 'Pakur'), ('Godda', 'Godda'), ('Sahebganj', 'Sahebganj'), ('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East Champaran', 'East Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Lakhisarai', 'Lakhisarai'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Madhepura', 'Madhepura'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Sheohar', 'Sheohar'), ('Sheikhpura', 'Sheikhpura'), ('Saran', 'Saran'), ('Sitamarhi', 'Sitamarhi'), ('Supaul', 'Supaul'), ('Siwan', 'Siwan'), ('Vaishali', 'Vaishali'), ('West Champaran', 'West Champaran'), ('Other', 'Other')], default='Patna', max_length=50)),
                ('car_owner_name', models.CharField(default='-', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('car_title',),
            },
        ),
    ]
