# Generated by Django 4.2.4 on 2023-08-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
