# Generated by Django 4.2.4 on 2023-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, default='car-images/default.jpeg', null=True, upload_to='car-images/'),
        ),
    ]
